export default {
    // ACTIONS
    FILTER_BY_NAME: 'FILTER_BY_NAME',
    FILTER_BY_HIGH_LOW: 'FILTER_BY_HIGH_LOW',
    FILTER_BY_LOW_HIGH: 'FILTER_BY_LOW_HIGH:',
    FILTER_BY_NONE: 'FILTER_BY_NONE',
    FILTER_BY_DATE: 'FILTER_BY_DATE',
    SEARCH_RECEIVE_DATA_ERROR: 'SEARCH_RECEIVE_DATA_ERROR',
    FILTER_RECEIVE_DATA_ERROR: 'FILTER_RECEIVE_DATA_ERROR',
    FILTER: 'FILTER',
    SEARCH: 'SEARCH' 
};
