export default {
    // ACTIONS
    FILTER_BY_HIGH_LOW: 'FILTER_BY_HIGH_LOW',
    FILTER_BY_LOW_HIGH: 'FILTER_BY_LOW_HIGH:',
    FILTER_BY_NONE: 'FILTER_BY_NONE',
    FILTER_BY_OLD_NEW: 'FILTER_BY_OLD_NEW',
    FILTER_BY_NEW_OLD: 'FILTER_BY_NEW_OLD',
    FILTER_BY_ENGINEERING: 'FILTER_BY_ENGINEERING',
    FILTER_BY_BUSINESS: 'FILTER_BY_BUSINESS',
    FILTER_BY_BIOLOGY: 'FILTER_BY_BIOLOGY',
    FILTER_BY_SOCIOLOGY: 'FILTER_BY_SOCIOLOGY',
    FILTER_BY_ENGLISH: 'FILTER_BY_ENGLISH',
    FILTER_BY_ACCOUNTING: 'FILTER_BY_ACCOUNTING',
    FILTER_BY_OTHER: 'FILTER_BY_OTHER',
    FILTER_BY_ISBN: 'FILTER_BY_ISBN',
    SEARCH_RECEIVE_DATA_ERROR: 'SEARCH_RECEIVE_DATA_ERROR',
    FILTER_RECEIVE_DATA_ERROR: 'FILTER_RECEIVE_DATA_ERROR',
    FILTER: 'FILTER',
    SEARCH: 'SEARCH' 
};
