export default {
    // ACTIONS
    FILTER_RECEIVE_DATA: 'FILTER_RECEIVE_DATA',
    FILTER_LIST_RECEIVE_DATA: 'FILTER_LIST_RECEIVE_DATA',
    FILTER_RECEIVE_DATA_ERROR: 'FILTER_RECEIVE_DATA_ERROR',
    FILTER_AWAIT_CREATION_RESPONSE: 'FILTER_AWAIT_CREATION_RESPONSE',
    FILTER_RECEIVE_CREATION_RESPONSE: 'FILTER_RECEIVE_CREATION_RESPONSE',
    FILTER_EDIT: 'FILTER_EDIT',
    FILTER_EDIT_FINISH: 'FILTER_EDIT_FINISH',
    FILTER_EDIT_SUBMIT: 'FILTER_EDIT_SUBMIT',
};
