export default {
    // ACTIONS
    MESSAGE_RECEIVE_DATA: 'MESSAGE_RECEIVE_DATA',
    MESSAGE_LIST_RECEIVE_DATA: 'MESSAGE_LIST_RECEIVE_DATA',
    MESSAGE_RECEIVE_DATA_ERROR: 'MESSAGE_RECEIVE_DATA_ERROR',
    MESSAGE_AWAIT_CREATION_RESPONSE: 'MESSAGE_AWAIT_CREATION_RESPONSE',
    MESSAGE_RECEIVE_CREATION_RESPONSE: 'MESSAGE_RECEIVE_CREATION_RESPONSE',
    MESSAGE_EDIT: 'MESSAGE_EDIT',
    MESSAGE_EDIT_FINISH: 'MESSAGE_EDIT_FINISH',
    MESSAGE_EDIT_SUBMIT: 'MESSAGE_EDIT_SUBMIT',
};
