export default {
	// ACTIONS
	POSTS_RECEIVE_DATA: 'POSTS_RECEIVE_DATA',
	POSTS_RECEIVE_DATA_ERROR: 'POSTS_RECEIVE_DATA_ERROR',
	WISHLIST_RECEIVE_DATA: 'WISHLIST_RECEIVE_DATA',
	WISHLIST_RECEIVE_DATA_ERROR: 'WISHLIST_RECEIVE_DATA_ERROR',
	POST_AWAIT_CREATION_RESPONSE: 'POST_AWAIT_CREATION_RESPONSE',
	POST_RECEIVE_CREATION_RESPONSE: 'POST_RECEIVE_CREATION_RESPONSE',
	POST_EDIT: 'POST_EDIT',
	POST_EDIT_FINISH: 'POST_EDIT_FINISH',
	POST_EDIT_SUBMIT: 'POST_EDIT_SUBMIT',
	POST_WISH_LIST: 'POST_WISH_LIST',

	// STATES
	POST_EDITING: 'POST_EDITING',
	POST_SUBMITTING: 'POST_SUBMITTING'
};
